export const FETCH_USER = "FETCH_USER";
export const UPDATE_USER = "UPDATE_USER";

export const FETCH_EVENT = "fetch_event";
export const CREATE_EVENT = "create_event";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const SAVE_REG_MODEL = "SAVE_REG_MODEL";
export const SAVE_EVENT_MODEL = "SAVE_EVENT_MODEL";
export const PUBLISH_REG_MODEL = "PUBLISH_REG_MODEL";
export const PUBLISH_EVENT_MODEL = "PUBLISH_EVENT_MODEL";

export const FETCH_PAGE_MODEL = "fetch_page_model";
export const MOVE_SECTION = "MOVE_SECTION";
export const DELETE_SECTION = "DELETE_SECTION";
export const MODEL_ISSAVED = "MODEL_ISSAVED";
export const ADD_SECTION = "add_section";
export const UPDATE_SECTION = "update_section";
export const FETCH_PUBLISHED_PAGE = "FETCH_PUBLISHED_PAGE";
export const FLAG_UPDATE = "FLAG_UPDATE";

export const SET_LOADED = "SET_LOADED";
export const SET_SIDE_DRAWER_OPEN = "SET_SIDE_DRAWER_OPEN";

export const FETCH_EVENT_LIST = "FETCH_EVENT_LIST";
export const DELETE_EVENT = "DELETE_EVENT";
export const DUPLICATE_EVENT = "DUPLICATE_EVENT";

export const UPDATE_REACT_COMPONENT = "UPDATE_REACT_COMPONENT";

export const FETCH_REGISTRATION = "FETCH_REGISTRATION";
export const FETCH_FORM = "FETCH_FORM";

export const FETCH_COMMUNICATION_LIST = "FETCH_COMMUNICATION_LIST";
export const FETCH_EMAIL_LIST = "FETCH_EMAIL_LIST";

export const FETCH_ATTENDEE = "FETCH_ATTENDEE";

export const TRIGGER_SECTION_REACT_UPDATE = "TRIGGER_SECTION_REACT_UPDATE";

export const FETCH_POLLS = "FETCH_POLLS";
export const SELECT_POLL_BY_INDEX = "SELECT_POLL_BY_INDEX";
export const FETCH_RESULTS = "FETCH_RESULTS";

export const SET_PERMISSIONS = "SET_PERMISSIONS";
